// SECTION USER
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// SECTION CART
export const TOOGLE_CART_HIDDEN = 'TOOGLE_CART_HIDDEN';
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
